// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShopApp.Data;

#nullable disable

namespace eShopApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eShopApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("eShopApp.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("eShopApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High performance laptop",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Laptop",
                            Name = "Laptop Pro",
                            Price = 1299.99m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ergonomic wireless mouse",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Mouse",
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 3,
                            Description = "RGB mechanical keyboard",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Keyboard",
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 4,
                            Description = "27 inch 4K monitor",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Monitor",
                            Name = "Monitor 4K",
                            Price = 499.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            Description = "7 port USB hub",
                            ImageUrl = "https://via.placeholder.com/300x200?text=USB+Hub",
                            Name = "USB Hub",
                            Price = 19.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 6,
                            Description = "1080p HD webcam",
                            ImageUrl = "https://via.placeholder.com/300x200?text=Webcam",
                            Name = "Webcam HD",
                            Price = 59.99m,
                            Stock = 30
                        });
                });

            modelBuilder.Entity("eShopApp.Models.OrderItem", b =>
                {
                    b.HasOne("eShopApp.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("eShopApp.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
